#!/usr/bin/env node
//   --proxy  the platform's reverse proxy (Dokploy/Traefik) terminates TLS: gateway serves plain HTTP
// Generates a ready-to-use .env for docker-compose.yml: random secrets plus the
// anon / service_role JWTs signed with the generated JWT secret (HS256).
//
//   node docker/generate-env.mjs [--url https://feedback.example.com] [--out .env] [--force]
//   docker run --rm -v "$PWD:/out" <image> gen-env --out /out/.env --url https://...

import { createHmac, randomBytes } from 'node:crypto'
import { existsSync, writeFileSync } from 'node:fs'

const args = process.argv.slice(2)
const flag = (name, fallback) => {
  const index = args.indexOf(name)
  return index === -1 ? fallback : args[index + 1]
}

const out = flag('--out', '.env')
const behindProxy = args.includes('--proxy') // Dokploy/Traefik terminates TLS
const url = (flag('--url', 'http://localhost:3000') ?? '').replace(/\/+$/, '')

if (!/^https?:\/\/[^/\s]+$/.test(url)) {
  console.error(`--url must look like https://feedback.example.com (got "${url}")`)
  process.exit(1)
}
if (existsSync(out) && !args.includes('--force')) {
  console.error(`${out} already exists. Pass --force to overwrite it (this rotates every secret).`)
  process.exit(1)
}

const b64url = (input) => Buffer.from(input).toString('base64url')
const hex = (bytes) => randomBytes(bytes).toString('hex')

const jwtSecret = hex(32)
const signJwt = (role) => {
  const header = b64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }))
  const now = Math.floor(Date.now() / 1000)
  const payload = b64url(JSON.stringify({ role, iss: 'supabase', iat: now, exp: now + 10 * 365 * 24 * 3600 }))
  const signature = createHmac('sha256', jwtSecret).update(`${header}.${payload}`).digest('base64url')
  return `${header}.${payload}.${signature}`
}

const host = new URL(url).host
const isLocal = /^(localhost|127\.0\.0\.1)(:\d+)?$/.test(host)

const lines = [
  '# Generated by docker/generate-env.mjs - keep this file private.',
  `APP_URL=${url}`,
  `# Hostname of APP_URL; requests for any other host are treated as customer custom domains.`,
  `APP_DOMAIN=${new URL(url).hostname}`,
  `# Caddy site address. ":80" serves plain HTTP; a bare domain enables automatic HTTPS.`,
  `SITE_ADDRESS=${isLocal || behindProxy ? ':80' : host}`,
  `HTTP_PORT=${isLocal ? new URL(url).port || '80' : '80'}`,
  `HTTPS_PORT=443`,
  '',
  `POSTGRES_PASSWORD=${hex(24)}`,
  `JWT_SECRET=${jwtSecret}`,
  `ANON_KEY=${signJwt('anon')}`,
  `SERVICE_ROLE_KEY=${signJwt('service_role')}`,
  `ENCRYPTION_KEY=${randomBytes(32).toString('base64')}`,
  `ACCESS_COOKIE_SECRET=${hex(32)}`,
  `IP_HASH_SALT=${hex(32)}`,
  `FEEDBACK_WEBHOOK_SECRET=${hex(32)}`,
  '',
  '# Sign-in methods shown on /login: magic_link, github, password.',
  '# "password" works without SMTP, so it is the default for self-hosting.',
  'AUTH_METHODS=password',
  '# Default interface language (en or ar). Visitors can switch it in the header.',
  'DEFAULT_LOCALE=ar',
  '',
  '# Skip email confirmation (set to false once SMTP is configured).',
  'AUTH_AUTOCONFIRM=true',
  'DISABLE_SIGNUP=false',
  'SMTP_HOST=',
  'SMTP_PORT=587',
  'SMTP_USER=',
  'SMTP_PASS=',
  'SMTP_ADMIN_EMAIL=',
  '',
  '# Optional: GitHub sign-in (add "github" to AUTH_METHODS).',
  'GITHUB_CLIENT_ID=',
  'GITHUB_CLIENT_SECRET=',
  '',
  '# Optional: custom-domain verification through Cloudflare.',
  'CLOUDFLARE_API_TOKEN=',
  'CLOUDFLARE_ACCOUNT_ID=',
  'CLOUDFLARE_ZONE_ID=',
  '',
  '# Image to run. Unset: docker-compose.yml builds linear-gratis:local, the Dokploy file pulls the published image.',
  '# LINEAR_GRATIS_IMAGE=<your-dockerhub-user>/linear-gratis:latest',
  '',
]

writeFileSync(out, lines.join('\n'), { mode: 0o600 })
console.log(`Wrote ${out}`)
